name: Docker Image v4 CI

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_IMAGE: "postgres:16-alpine"
      CLAIR_VERSION: "4.7.4"
      CLAIR_LOCAL_SCAN_IMAGE: "arminc/clair-local-scan-v4"
      ARCHS: "linux/amd64,linux/arm64"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Runner diskspace workaround
        run: |
          # Symlink docker image and containers folders to /mnt (GitHub Action space limitation work around)
          docker system prune -a -f
          sudo systemctl stop docker
          sudo mv /var/lib/docker /mnt/docker

          json_content='{ 
            "exec-opts": ["native.cgroupdriver=cgroupfs"],
            "cgroup-parent": "/actions_job",
            "data-root": "/mnt/docker"
          }'

          echo "$json_content" > /tmp/daemon.json
          sudo mv /tmp/daemon.json /etc/docker/daemon.json
          sudo rm -fr /var/lib/docker
          sudo systemctl start docker

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          install: true

      - name: Login to DockerHub
        if: github.repository_owner == 'arminc'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker buildx create --use --name multiarch_builder || docker buildx use multiarch_builder
          docker buildx build --platform "${ARCHS}" -t "${CLAIR_LOCAL_SCAN_IMAGE}:latest" -t "${CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${GITHUB_SHA}" --build-arg VERSION="${CLAIR_VERSION}" --push clair/v4

      - name: Start Postgres and run clair
        run: |
          chmod a+x ./postgres/*.sh
          ./postgres/setup_base.sh
      
      - name: Docker Postgres info
        run: |
          docker logs postgres

      - name: Docker Clair info
        run: |
          docker logs clair

      - name: Checking
        run: |
          ./clair/v4/check.sh

      - name: Docker logs
        run: |
          docker logs clair

      - name: Stop containers
        run: |
          docker stop clair
          docker stop postgres

      - name: Create postgres container
        run: |
          ./postgres/create_container.sh
